

module.exports=[
    {
      "city": "Delhi", 
      "latituide": "28.6100", 
      "longituide": "77.2300", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Delhi", 
      "capital": "admin", 
      "population": "32226000", 
      "population_proper": "16753235"
    }, 
    {
      "city": "Mumbai", 
      "latituide": "19.0761", 
      "longituide": "72.8775", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Mahārāshtra", 
      "capital": "admin", 
      "population": "24973000", 
      "population_proper": "12478447"
    }, 
    {
      "city": "Kolkāta", 
      "latituide": "22.5675", 
      "longituide": "88.3700", 
      "country": "India", 
      "iso2": "IN", 
      "state": "West Bengal", 
      "capital": "admin", 
      "population": "18502000", 
      "population_proper": "4496694"
    }, 
    {
      "city": "Bangalore", 
      "latituide": "12.9789", 
      "longituide": "77.5917", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Karnātaka", 
      "capital": "admin", 
      "population": "15386000", 
      "population_proper": "8443675"
    }, 
    {
      "city": "Chennai", 
      "latituide": "13.0825", 
      "longituide": "80.2750", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Tamil Nādu", 
      "capital": "admin", 
      "population": "12395000", 
      "population_proper": "6727000"
    }, 
    {
      "city": "Hyderābād", 
      "latituide": "17.3617", 
      "longituide": "78.4747", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Telangāna", 
      "capital": "admin", 
      "population": "10494000", 
      "population_proper": "6993262"
    }, 
    {
      "city": "Pune", 
      "latituide": "18.5203", 
      "longituide": "73.8567", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Mahārāshtra", 
      "capital": "", 
      "population": "8231000", 
      "population_proper": "3124458"
    }, 
    {
      "city": "Ahmedabad", 
      "latituide": "23.0225", 
      "longituide": "72.5714", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Gujarāt", 
      "capital": "minor", 
      "population": "8009000", 
      "population_proper": "5570585"
    }, 
    {
      "city": "Sūrat", 
      "latituide": "21.1702", 
      "longituide": "72.8311", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Gujarāt", 
      "capital": "", 
      "population": "6538000", 
      "population_proper": "4466826"
    }, 
    {
      "city": "Lucknow", 
      "latituide": "26.8500", 
      "longituide": "80.9500", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Uttar Pradesh", 
      "capital": "admin", 
      "population": "3382000", 
      "population_proper": "3382000"
    }, 
    {
      "city": "Jaipur", 
      "latituide": "26.9000", 
      "longituide": "75.8000", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Rājasthān", 
      "capital": "admin", 
      "population": "3073350", 
      "population_proper": "3073350"
    }, 
    {
      "city": "Kanpur", 
      "latituide": "26.4499", 
      "longituide": "80.3319", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Uttar Pradesh", 
      "capital": "", 
      "population": "2701324", 
      "population_proper": "2701324"
    }, 
    {
      "city": "Mirzāpur", 
      "latituide": "25.1460", 
      "longituide": "82.5690", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Uttar Pradesh", 
      "capital": "", 
      "population": "2496970", 
      "population_proper": "2496970"
    }, 
    {
      "city": "Nāgpur", 
      "latituide": "21.1497", 
      "longituide": "79.0806", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Mahārāshtra", 
      "capital": "", 
      "population": "2405665", 
      "population_proper": "2405665"
    }, 
    {
      "city": "Ghāziābād", 
      "latituide": "28.6700", 
      "longituide": "77.4200", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Uttar Pradesh", 
      "capital": "", 
      "population": "2375820", 
      "population_proper": "2375820"
    }, 
    {
      "city": "Supaul", 
      "latituide": "26.1260", 
      "longituide": "86.6050", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Bihār", 
      "capital": "", 
      "population": "2229076", 
      "population_proper": "2229076"
    }, 
    {
      "city": "Vadodara", 
      "latituide": "22.3000", 
      "longituide": "73.2000", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Gujarāt", 
      "capital": "", 
      "population": "2065771", 
      "population_proper": "2065771"
    }, 
    {
      "city": "Rājkot", 
      "latituide": "22.3000", 
      "longituide": "70.7833", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Gujarāt", 
      "capital": "", 
      "population": "2043000", 
      "population_proper": "2043000"
    }, 
    {
      "city": "Vishākhapatnam", 
      "latituide": "17.7042", 
      "longituide": "83.2978", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Andhra Pradesh", 
      "capital": "", 
      "population": "2035922", 
      "population_proper": "2035922"
    }, 
    {
      "city": "Indore", 
      "latituide": "22.7167", 
      "longituide": "75.8472", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Madhya Pradesh", 
      "capital": "", 
      "population": "1994397", 
      "population_proper": "1994397"
    }, 
    {
      "city": "Thāne", 
      "latituide": "19.1972", 
      "longituide": "72.9722", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Mahārāshtra", 
      "capital": "", 
      "population": "1886941", 
      "population_proper": "1886941"
    }, 
    {
      "city": "Bhopāl", 
      "latituide": "23.2599", 
      "longituide": "77.4126", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Madhya Pradesh", 
      "capital": "admin", 
      "population": "1798218", 
      "population_proper": "1798218"
    }, 
    {
      "city": "Pimpri-Chinchwad", 
      "latituide": "18.6186", 
      "longituide": "73.8037", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Mahārāshtra", 
      "capital": "", 
      "population": "1727692", 
      "population_proper": "1727692"
    }, 
    {
      "city": "Patna", 
      "latituide": "25.5940", 
      "longituide": "85.1376", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Bihār", 
      "capital": "admin", 
      "population": "1684222", 
      "population_proper": "1684222"
    }, 
    {
      "city": "Bilāspur", 
      "latituide": "22.0900", 
      "longituide": "82.1500", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Chhattīsgarh", 
      "capital": "", 
      "population": "1625502", 
      "population_proper": "1625502"
    }, 
    {
      "city": "Ludhiāna", 
      "latituide": "30.9100", 
      "longituide": "75.8500", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Punjab", 
      "capital": "", 
      "population": "1618879", 
      "population_proper": "1618879"
    }, 
    {
      "city": "Āgra", 
      "latituide": "27.1800", 
      "longituide": "78.0200", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Uttar Pradesh", 
      "capital": "", 
      "population": "1585704", 
      "population_proper": "1585704"
    }, 
    {
      "city": "Madurai", 
      "latituide": "9.9252", 
      "longituide": "78.1198", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Tamil Nādu", 
      "capital": "minor", 
      "population": "1561129", 
      "population_proper": "1561129"
    }, 
    {
      "city": "Jamshedpur", 
      "latituide": "22.7925", 
      "longituide": "86.1842", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Jhārkhand", 
      "capital": "", 
      "population": "1558000", 
      "population_proper": "1558000"
    }, 
    {
      "city": "Prayagraj", 
      "latituide": "25.4358", 
      "longituide": "81.8464", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Uttar Pradesh", 
      "capital": "", 
      "population": "1536218", 
      "population_proper": "1536218"
    }, 
    {
      "city": "Nāsik", 
      "latituide": "19.9975", 
      "longituide": "73.7898", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Mahārāshtra", 
      "capital": "", 
      "population": "1486053", 
      "population_proper": "1486053"
    }, 
    {
      "city": "Farīdābād", 
      "latituide": "28.4211", 
      "longituide": "77.3078", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Haryāna", 
      "capital": "", 
      "population": "1414050", 
      "population_proper": "1414050"
    }, 
    {
      "city": "Meerut", 
      "latituide": "28.9800", 
      "longituide": "77.7100", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Uttar Pradesh", 
      "capital": "", 
      "population": "1305429", 
      "population_proper": "1305429"
    }, 
    {
      "city": "Jabalpur", 
      "latituide": "23.1667", 
      "longituide": "79.9333", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Madhya Pradesh", 
      "capital": "", 
      "population": "1267564", 
      "population_proper": "1267564"
    }, 
    {
      "city": "Kalyān", 
      "latituide": "19.2502", 
      "longituide": "73.1602", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Mahārāshtra", 
      "capital": "", 
      "population": "1246381", 
      "population_proper": "1246381"
    }, 
    {
      "city": "Vasai-Virar", 
      "latituide": "19.3607", 
      "longituide": "72.7956", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Mahārāshtra", 
      "capital": "", 
      "population": "1221233", 
      "population_proper": "1221233"
    }, 
    {
      "city": "Najafgarh", 
      "latituide": "28.6092", 
      "longituide": "76.9798", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Delhi", 
      "capital": "", 
      "population": "1203180", 
      "population_proper": "1203180"
    }, 
    {
      "city": "Vārānasi", 
      "latituide": "25.3189", 
      "longituide": "83.0128", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Uttar Pradesh", 
      "capital": "", 
      "population": "1198491", 
      "population_proper": "1198491"
    }, 
    {
      "city": "Srīnagar", 
      "latituide": "34.0900", 
      "longituide": "74.7900", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Jammu and Kashmīr", 
      "capital": "admin", 
      "population": "1180570", 
      "population_proper": "1180570"
    }, 
    {
      "city": "Aurangābād", 
      "latituide": "19.8800", 
      "longituide": "75.3200", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Mahārāshtra", 
      "capital": "", 
      "population": "1175116", 
      "population_proper": "1175116"
    }, 
    {
      "city": "Dhanbād", 
      "latituide": "23.7998", 
      "longituide": "86.4305", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Jhārkhand", 
      "capital": "", 
      "population": "1162472", 
      "population_proper": "1162472"
    }, 
    {
      "city": "Amritsar", 
      "latituide": "31.6400", 
      "longituide": "74.8600", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Punjab", 
      "capital": "", 
      "population": "1132383", 
      "population_proper": "1132383"
    }, 
    {
      "city": "Alīgarh", 
      "latituide": "27.8800", 
      "longituide": "78.0800", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Uttar Pradesh", 
      "capital": "", 
      "population": "1131160", 
      "population_proper": "1131160"
    }, 
    {
      "city": "Guwāhāti", 
      "latituide": "26.1722", 
      "longituide": "91.7458", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Assam", 
      "capital": "", 
      "population": "1116267", 
      "population_proper": "1116267"
    }, 
    {
      "city": "Hāora", 
      "latituide": "22.5800", 
      "longituide": "88.3294", 
      "country": "India", 
      "iso2": "IN", 
      "state": "West Bengal", 
      "capital": "", 
      "population": "1077075", 
      "population_proper": "1077075"
    }, 
    {
      "city": "Rānchi", 
      "latituide": "23.3600", 
      "longituide": "85.3300", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Jhārkhand", 
      "capital": "admin", 
      "population": "1073440", 
      "population_proper": "1073440"
    }, 
    {
      "city": "Gwalior", 
      "latituide": "26.2124", 
      "longituide": "78.1772", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Madhya Pradesh", 
      "capital": "", 
      "population": "1069276", 
      "population_proper": "1069276"
    }, 
    {
      "city": "Chandīgarh", 
      "latituide": "30.7500", 
      "longituide": "76.7800", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Chandīgarh", 
      "capital": "admin", 
      "population": "1055450", 
      "population_proper": "1055450"
    }, 
    {
      "city": "Haldwāni", 
      "latituide": "29.2200", 
      "longituide": "79.5200", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Uttarākhand", 
      "capital": "", 
      "population": "1050000", 
      "population_proper": "1050000"
    }, 
    {
      "city": "Vijayavāda", 
      "latituide": "16.5193", 
      "longituide": "80.6305", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Andhra Pradesh", 
      "capital": "", 
      "population": "1048240", 
      "population_proper": "1048240"
    }, 
    {
      "city": "Jodhpur", 
      "latituide": "26.2800", 
      "longituide": "73.0200", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Rājasthān", 
      "capital": "", 
      "population": "1033918", 
      "population_proper": "1033918"
    }, 
    {
      "city": "Raipur", 
      "latituide": "21.2444", 
      "longituide": "81.6306", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Chhattīsgarh", 
      "capital": "admin", 
      "population": "1010087", 
      "population_proper": "1010087"
    }, 
    {
      "city": "Kota", 
      "latituide": "25.1800", 
      "longituide": "75.8300", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Rājasthān", 
      "capital": "", 
      "population": "1001694", 
      "population_proper": "1001694"
    }, 
    {
      "city": "Bhayandar", 
      "latituide": "19.2900", 
      "longituide": "72.8500", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Mahārāshtra", 
      "capital": "", 
      "population": "809378", 
      "population_proper": "809378"
    }, 
    {
      "city": "Loni", 
      "latituide": "28.7500", 
      "longituide": "77.2800", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Uttar Pradesh", 
      "capital": "", 
      "population": "516082", 
      "population_proper": "516082"
    }, 
    {
      "city": "Ambattūr", 
      "latituide": "13.1143", 
      "longituide": "80.1548", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Tamil Nādu", 
      "capital": "", 
      "population": "466205", 
      "population_proper": "466205"
    }, 
    {
      "city": "Salt Lake City", 
      "latituide": "22.6100", 
      "longituide": "88.4000", 
      "country": "India", 
      "iso2": "IN", 
      "state": "West Bengal", 
      "capital": "", 
      "population": "403316", 
      "population_proper": "403316"
    }, 
    {
      "city": "Bhātpāra", 
      "latituide": "22.8700", 
      "longituide": "88.4100", 
      "country": "India", 
      "iso2": "IN", 
      "state": "West Bengal", 
      "capital": "", 
      "population": "386019", 
      "population_proper": "386019"
    }, 
    {
      "city": "Kūkatpalli", 
      "latituide": "17.4849", 
      "longituide": "78.4138", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Telangāna", 
      "capital": "", 
      "population": "385821", 
      "population_proper": "385821"
    }, 
    {
      "city": "Dāsarhalli", 
      "latituide": "13.0465", 
      "longituide": "77.5130", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Karnātaka", 
      "capital": "", 
      "population": "349720", 
      "population_proper": "349720"
    }, 
    {
      "city": "Muzaffarpur", 
      "latituide": "26.1225", 
      "longituide": "85.3906", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Bihār", 
      "capital": "", 
      "population": "333200", 
      "population_proper": "333200"
    }, 
    {
      "city": "Oulgaret", 
      "latituide": "11.9570", 
      "longituide": "79.7737", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Tamil Nādu", 
      "capital": "", 
      "population": "300104", 
      "population_proper": "300104"
    }, 
    {
      "city": "New Delhi", 
      "latituide": "28.6139", 
      "longituide": "77.2089", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Delhi", 
      "capital": "primary", 
      "population": "249998", 
      "population_proper": "249998"
    }, 
    {
      "city": "Tiruvottiyūr", 
      "latituide": "13.1600", 
      "longituide": "80.3000", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Tamil Nādu", 
      "capital": "", 
      "population": "249446", 
      "population_proper": "249446"
    }, 
    {
      "city": "Puducherry", 
      "latituide": "11.9167", 
      "longituide": "79.8167", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Puducherry", 
      "capital": "admin", 
      "population": "244377", 
      "population_proper": "244377"
    }, 
    {
      "city": "Byatarayanpur", 
      "latituide": "13.0659", 
      "longituide": "77.5922", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Karnātaka", 
      "capital": "", 
      "population": "239902", 
      "population_proper": "239902"
    }, 
    {
      "city": "Pallāvaram", 
      "latituide": "12.9675", 
      "longituide": "80.1491", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Tamil Nādu", 
      "capital": "", 
      "population": "215417", 
      "population_proper": "215417"
    }, 
    {
      "city": "Secunderābād", 
      "latituide": "17.4399", 
      "longituide": "78.4983", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Telangāna", 
      "capital": "", 
      "population": "213698", 
      "population_proper": "213698"
    }, 
    {
      "city": "Shimla", 
      "latituide": "31.1033", 
      "longituide": "77.1722", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Himāchal Pradesh", 
      "capital": "admin", 
      "population": "206575", 
      "population_proper": "206575"
    }, 
    {
      "city": "Puri", 
      "latituide": "19.8000", 
      "longituide": "85.8167", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Odisha", 
      "capital": "", 
      "population": "201026", 
      "population_proper": "201026"
    }, 
    {
      "city": "Murtazābād", 
      "latituide": "28.7111", 
      "longituide": "77.2688", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Uttar Pradesh", 
      "capital": "", 
      "population": "189117", 
      "population_proper": "189117"
    }, 
    {
      "city": "Shrīrāmpur", 
      "latituide": "22.7500", 
      "longituide": "88.3400", 
      "country": "India", 
      "iso2": "IN", 
      "state": "West Bengal", 
      "capital": "", 
      "population": "181842", 
      "population_proper": "181842"
    }, 
    {
      "city": "Chandannagar", 
      "latituide": "22.8700", 
      "longituide": "88.3800", 
      "country": "India", 
      "iso2": "IN", 
      "state": "West Bengal", 
      "capital": "", 
      "population": "166867", 
      "population_proper": "166867"
    }, 
    {
      "city": "Sultānpur Mazra", 
      "latituide": "28.6981", 
      "longituide": "77.0689", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Delhi", 
      "capital": "", 
      "population": "163716", 
      "population_proper": "163716"
    }, 
    {
      "city": "Krishnanagar", 
      "latituide": "23.4000", 
      "longituide": "88.5000", 
      "country": "India", 
      "iso2": "IN", 
      "state": "West Bengal", 
      "capital": "", 
      "population": "153062", 
      "population_proper": "153062"
    }, 
    {
      "city": "Bārākpur", 
      "latituide": "22.7600", 
      "longituide": "88.3700", 
      "country": "India", 
      "iso2": "IN", 
      "state": "West Bengal", 
      "capital": "", 
      "population": "152783", 
      "population_proper": "152783"
    }, 
    {
      "city": "Bhālswa Jahangirpur", 
      "latituide": "28.7354", 
      "longituide": "77.1638", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Delhi", 
      "capital": "", 
      "population": "151427", 
      "population_proper": "151427"
    }, 
    {
      "city": "Nāngloi Jāt", 
      "latituide": "28.6833", 
      "longituide": "77.0667", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Delhi", 
      "capital": "", 
      "population": "150371", 
      "population_proper": "150371"
    }, 
    {
      "city": "Balasore", 
      "latituide": "21.5033", 
      "longituide": "86.9250", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Odisha", 
      "capital": "", 
      "population": "144373", 
      "population_proper": "144373"
    }, 
    {
      "city": "Dalūpura", 
      "latituide": "28.6004", 
      "longituide": "77.3194", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Delhi", 
      "capital": "", 
      "population": "132628", 
      "population_proper": "132628"
    }, 
    {
      "city": "Yelahanka", 
      "latituide": "13.1007", 
      "longituide": "77.5963", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Karnātaka", 
      "capital": "", 
      "population": "119891", 
      "population_proper": "119891"
    }, 
    {
      "city": "Titāgarh", 
      "latituide": "22.7400", 
      "longituide": "88.3700", 
      "country": "India", 
      "iso2": "IN", 
      "state": "West Bengal", 
      "capital": "", 
      "population": "116541", 
      "population_proper": "116541"
    }, 
    {
      "city": "Dam Dam", 
      "latituide": "22.6200", 
      "longituide": "88.4200", 
      "country": "India", 
      "iso2": "IN", 
      "state": "West Bengal", 
      "capital": "", 
      "population": "114786", 
      "population_proper": "114786"
    }, 
    {
      "city": "Bānsbāria", 
      "latituide": "22.9700", 
      "longituide": "88.4000", 
      "country": "India", 
      "iso2": "IN", 
      "state": "West Bengal", 
      "capital": "", 
      "population": "103920", 
      "population_proper": "103920"
    }, 
    {
      "city": "Madhavaram", 
      "latituide": "13.1482", 
      "longituide": "80.2314", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Tamil Nādu", 
      "capital": "", 
      "population": "100442", 
      "population_proper": "100442"
    }, 
    {
      "city": "Abbigeri", 
      "latituide": "13.0767", 
      "longituide": "77.5250", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Karnātaka", 
      "capital": "", 
      "population": "100000", 
      "population_proper": "100000"
    }, 
    {
      "city": "Baj Baj", 
      "latituide": "22.4828", 
      "longituide": "88.1818", 
      "country": "India", 
      "iso2": "IN", 
      "state": "West Bengal", 
      "capital": "", 
      "population": "76837", 
      "population_proper": "76837"
    }, 
    {
      "city": "Garhi", 
      "latituide": "28.6317", 
      "longituide": "77.3186", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Uttar Pradesh", 
      "capital": "", 
      "population": "75544", 
      "population_proper": "75544"
    }, 
    {
      "city": "Mīrpeta", 
      "latituide": "17.3200", 
      "longituide": "78.5200", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Telangāna", 
      "capital": "", 
      "population": "66982", 
      "population_proper": "66982"
    }, 
    {
      "city": "Nerkunram", 
      "latituide": "13.0619", 
      "longituide": "80.2094", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Tamil Nādu", 
      "capital": "", 
      "population": "52570", 
      "population_proper": "52570"
    }, 
    {
      "city": "Kendrāparha", 
      "latituide": "20.5000", 
      "longituide": "86.4200", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Odisha", 
      "capital": "", 
      "population": "41404", 
      "population_proper": "41404"
    }, 
    {
      "city": "Sijua", 
      "latituide": "23.7762", 
      "longituide": "86.3303", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Jhārkhand", 
      "capital": "", 
      "population": "39372", 
      "population_proper": "39372"
    }, 
    {
      "city": "Manali", 
      "latituide": "13.1667", 
      "longituide": "80.2667", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Tamil Nādu", 
      "capital": "", 
      "population": "37748", 
      "population_proper": "37748"
    }, 
    {
      "city": "Kānkuria", 
      "latituide": "24.6523", 
      "longituide": "87.9604", 
      "country": "India", 
      "iso2": "IN", 
      "state": "West Bengal", 
      "capital": "", 
      "population": "36925", 
      "population_proper": "36925"
    }, 
    {
      "city": "Chakapara", 
      "latituide": "22.6300", 
      "longituide": "88.3500", 
      "country": "India", 
      "iso2": "IN", 
      "state": "West Bengal", 
      "capital": "", 
      "population": "35282", 
      "population_proper": "35282"
    }, 
    {
      "city": "Pāppākurichchi", 
      "latituide": "10.8137", 
      "longituide": "78.7481", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Tamil Nādu", 
      "capital": "", 
      "population": "26889", 
      "population_proper": "26889"
    }, 
    {
      "city": "Herohalli", 
      "latituide": "12.9911", 
      "longituide": "77.4873", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Karnātaka", 
      "capital": "", 
      "population": "23851", 
      "population_proper": "23851"
    }, 
    {
      "city": "Madipakkam", 
      "latituide": "12.9623", 
      "longituide": "80.1986", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Tamil Nādu", 
      "capital": "", 
      "population": "20523", 
      "population_proper": "20523"
    }, 
    {
      "city": "Sabalpur", 
      "latituide": "25.6053", 
      "longituide": "85.1835", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Bihār", 
      "capital": "", 
      "population": "18810", 
      "population_proper": "18810"
    }, 
    {
      "city": "Bāuria", 
      "latituide": "22.4521", 
      "longituide": "88.1853", 
      "country": "India", 
      "iso2": "IN", 
      "state": "West Bengal", 
      "capital": "", 
      "population": "16764", 
      "population_proper": "16764"
    }, 
    {
      "city": "Salua", 
      "latituide": "22.6100", 
      "longituide": "88.2700", 
      "country": "India", 
      "iso2": "IN", 
      "state": "West Bengal", 
      "capital": "", 
      "population": "15171", 
      "population_proper": "15171"
    }, 
    {
      "city": "Chik Bānavar", 
      "latituide": "13.0846", 
      "longituide": "77.5014", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Karnātaka", 
      "capital": "", 
      "population": "14409", 
      "population_proper": "14409"
    }, 
    {
      "city": "Jālhalli", 
      "latituide": "13.0333", 
      "longituide": "77.5500", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Karnātaka", 
      "capital": "", 
      "population": "13063", 
      "population_proper": "13063"
    }, 
    {
      "city": "Chinnasekkadu", 
      "latituide": "13.1609", 
      "longituide": "80.2573", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Tamil Nādu", 
      "capital": "", 
      "population": "12854", 
      "population_proper": "12854"
    }, 
    {
      "city": "Jethuli", 
      "latituide": "25.5378", 
      "longituide": "85.2841", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Bihār", 
      "capital": "", 
      "population": "11572", 
      "population_proper": "11572"
    }, 
    {
      "city": "Nagtala", 
      "latituide": "22.4667", 
      "longituide": "88.3833", 
      "country": "India", 
      "iso2": "IN", 
      "state": "West Bengal", 
      "capital": "", 
      "population": "10419", 
      "population_proper": "10419"
    }, 
    {
      "city": "Pakri", 
      "latituide": "25.5876", 
      "longituide": "85.1580", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Bihār", 
      "capital": "", 
      "population": "9768", 
      "population_proper": "9768"
    }, 
    {
      "city": "Hunasamaranhalli", 
      "latituide": "13.1435", 
      "longituide": "77.6200", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Karnātaka", 
      "capital": "", 
      "population": "9741", 
      "population_proper": "9741"
    }, 
    {
      "city": "Hesarghatta", 
      "latituide": "13.1391", 
      "longituide": "77.4783", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Karnātaka", 
      "capital": "", 
      "population": "9485", 
      "population_proper": "9485"
    }, 
    {
      "city": "Bommayapālaiyam", 
      "latituide": "11.9922", 
      "longituide": "79.8499", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Tamil Nādu", 
      "capital": "", 
      "population": "8796", 
      "population_proper": "8796"
    }, 
    {
      "city": "Gundūr", 
      "latituide": "10.7339", 
      "longituide": "78.7184", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Tamil Nādu", 
      "capital": "", 
      "population": "8587", 
      "population_proper": "8587"
    }, 
    {
      "city": "Punādih", 
      "latituide": "25.5484", 
      "longituide": "85.2649", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Bihār", 
      "capital": "", 
      "population": "8273", 
      "population_proper": "8273"
    }, 
    {
      "city": "Harilādih", 
      "latituide": "23.7333", 
      "longituide": "86.4000", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Jhārkhand", 
      "capital": "", 
      "population": "7917", 
      "population_proper": "7917"
    }, 
    {
      "city": "Alāwalpur", 
      "latituide": "25.4958", 
      "longituide": "85.2021", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Bihār", 
      "capital": "", 
      "population": "7827", 
      "population_proper": "7827"
    }, 
    {
      "city": "Mādnāikanhalli", 
      "latituide": "13.0626", 
      "longituide": "77.4642", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Karnātaka", 
      "capital": "", 
      "population": "7805", 
      "population_proper": "7805"
    }, 
    {
      "city": "Bāgalūr", 
      "latituide": "13.1330", 
      "longituide": "77.6660", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Karnātaka", 
      "capital": "", 
      "population": "7519", 
      "population_proper": "7519"
    }, 
    {
      "city": "Kādiganahalli", 
      "latituide": "13.1687", 
      "longituide": "77.6283", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Karnātaka", 
      "capital": "", 
      "population": "7225", 
      "population_proper": "7225"
    }, 
    {
      "city": "Khānpur Zabti", 
      "latituide": "28.7103", 
      "longituide": "77.2781", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Uttar Pradesh", 
      "capital": "", 
      "population": "6994", 
      "population_proper": "6994"
    }, 
    {
      "city": "Mahuli", 
      "latituide": "25.5430", 
      "longituide": "85.2268", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Bihār", 
      "capital": "", 
      "population": "6683", 
      "population_proper": "6683"
    }, 
    {
      "city": "Zeyādah Kot", 
      "latituide": "22.4445", 
      "longituide": "88.3345", 
      "country": "India", 
      "iso2": "IN", 
      "state": "West Bengal", 
      "capital": "", 
      "population": "6457", 
      "population_proper": "6457"
    }, 
    {
      "city": "Arshakunti", 
      "latituide": "13.0785", 
      "longituide": "77.4225", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Karnātaka", 
      "capital": "", 
      "population": "6262", 
      "population_proper": "6262"
    }, 
    {
      "city": "Mirchi", 
      "latituide": "25.5554", 
      "longituide": "85.2139", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Bihār", 
      "capital": "", 
      "population": "5710", 
      "population_proper": "5710"
    }, 
    {
      "city": "Sonudih", 
      "latituide": "25.1155", 
      "longituide": "87.0214", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Bihār", 
      "capital": "", 
      "population": "5658", 
      "population_proper": "5658"
    }, 
    {
      "city": "Bayandhalli", 
      "latituide": "12.9779", 
      "longituide": "77.5688", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Karnātaka", 
      "capital": "", 
      "population": "5118", 
      "population_proper": "5118"
    }, 
    {
      "city": "Sondekoppa", 
      "latituide": "13.0000", 
      "longituide": "77.3667", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Karnātaka", 
      "capital": "", 
      "population": "4866", 
      "population_proper": "4866"
    }, 
    {
      "city": "Babura", 
      "latituide": "25.0851", 
      "longituide": "87.1092", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Bihār", 
      "capital": "", 
      "population": "4755", 
      "population_proper": "4755"
    }, 
    {
      "city": "Mādavar", 
      "latituide": "13.0525", 
      "longituide": "77.4732", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Karnātaka", 
      "capital": "", 
      "population": "4678", 
      "population_proper": "4678"
    }, 
    {
      "city": "Kadabgeri", 
      "latituide": "12.9965", 
      "longituide": "77.4331", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Karnātaka", 
      "capital": "", 
      "population": "4573", 
      "population_proper": "4573"
    }, 
    {
      "city": "Nanmangalam", 
      "latituide": "12.9381", 
      "longituide": "80.1753", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Tamil Nādu", 
      "capital": "", 
      "population": "4386", 
      "population_proper": "4386"
    }, 
    {
      "city": "Taliganja", 
      "latituide": "22.5041", 
      "longituide": "88.3598", 
      "country": "India", 
      "iso2": "IN", 
      "state": "West Bengal", 
      "capital": "", 
      "population": "4278", 
      "population_proper": "4278"
    }, 
    {
      "city": "Tarchha", 
      "latituide": "25.1116", 
      "longituide": "87.0964", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Bihār", 
      "capital": "", 
      "population": "4198", 
      "population_proper": "4198"
    }, 
    {
      "city": "Belgharia", 
      "latituide": "22.6581", 
      "longituide": "88.3852", 
      "country": "India", 
      "iso2": "IN", 
      "state": "West Bengal", 
      "capital": "", 
      "population": "4193", 
      "population_proper": "4193"
    }, 
    {
      "city": "Kammanhalli", 
      "latituide": "13.0155", 
      "longituide": "77.6381", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Karnātaka", 
      "capital": "", 
      "population": "4144", 
      "population_proper": "4144"
    }, 
    {
      "city": "Ambāpuram", 
      "latituide": "16.5990", 
      "longituide": "80.8938", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Andhra Pradesh", 
      "capital": "", 
      "population": "4110", 
      "population_proper": "4110"
    }, 
    {
      "city": "Sonnappanhalli", 
      "latituide": "13.1557", 
      "longituide": "77.6179", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Karnātaka", 
      "capital": "", 
      "population": "3996", 
      "population_proper": "3996"
    }, 
    {
      "city": "Kedihāti", 
      "latituide": "22.6508", 
      "longituide": "88.4608", 
      "country": "India", 
      "iso2": "IN", 
      "state": "West Bengal", 
      "capital": "", 
      "population": "3910", 
      "population_proper": "3910"
    }, 
    {
      "city": "Doddajīvanhalli", 
      "latituide": "13.0086", 
      "longituide": "77.6143", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Karnātaka", 
      "capital": "", 
      "population": "3792", 
      "population_proper": "3792"
    }, 
    {
      "city": "Simli Murārpur", 
      "latituide": "25.5792", 
      "longituide": "85.2401", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Bihār", 
      "capital": "", 
      "population": "3739", 
      "population_proper": "3739"
    }, 
    {
      "city": "Sonāwān", 
      "latituide": "25.5445", 
      "longituide": "85.2387", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Bihār", 
      "capital": "", 
      "population": "3682", 
      "population_proper": "3682"
    }, 
    {
      "city": "Devanandapur", 
      "latituide": "22.9326", 
      "longituide": "88.3729", 
      "country": "India", 
      "iso2": "IN", 
      "state": "West Bengal", 
      "capital": "", 
      "population": "3449", 
      "population_proper": "3449"
    }, 
    {
      "city": "Tribeni", 
      "latituide": "22.9867", 
      "longituide": "88.3987", 
      "country": "India", 
      "iso2": "IN", 
      "state": "West Bengal", 
      "capital": "", 
      "population": "3305", 
      "population_proper": "3305"
    }, 
    {
      "city": "Huttanhalli", 
      "latituide": "13.1651", 
      "longituide": "77.6512", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Karnātaka", 
      "capital": "", 
      "population": "3240", 
      "population_proper": "3240"
    }, 
    {
      "city": "Nathupur", 
      "latituide": "25.5163", 
      "longituide": "85.2544", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Bihār", 
      "capital": "", 
      "population": "3129", 
      "population_proper": "3129"
    }, 
    {
      "city": "Bāli", 
      "latituide": "25.4810", 
      "longituide": "85.2227", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Bihār", 
      "capital": "", 
      "population": "3128", 
      "population_proper": "3128"
    }, 
    {
      "city": "Vājarhalli", 
      "latituide": "13.1022", 
      "longituide": "77.4111", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Karnātaka", 
      "capital": "", 
      "population": "3009", 
      "population_proper": "3009"
    }, 
    {
      "city": "Alija Kotla", 
      "latituide": "17.2333", 
      "longituide": "78.5500", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Telangāna", 
      "capital": "", 
      "population": "3000", 
      "population_proper": "3000"
    }, 
    {
      "city": "Saino", 
      "latituide": "25.1134", 
      "longituide": "87.0108", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Bihār", 
      "capital": "", 
      "population": "2987", 
      "population_proper": "2987"
    }, 
    {
      "city": "Shekhpura", 
      "latituide": "25.5725", 
      "longituide": "85.1428", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Bihār", 
      "capital": "", 
      "population": "2950", 
      "population_proper": "2950"
    }, 
    {
      "city": "Cāchohalli", 
      "latituide": "13.0010", 
      "longituide": "77.4717", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Karnātaka", 
      "capital": "", 
      "population": "2946", 
      "population_proper": "2946"
    }, 
    {
      "city": "Andheri", 
      "latituide": "19.2104", 
      "longituide": "73.0464", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Mahārāshtra", 
      "capital": "", 
      "population": "2937", 
      "population_proper": "2937"
    }, 
    {
      "city": "Nārāyanpur Kola", 
      "latituide": "25.1293", 
      "longituide": "87.0076", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Bihār", 
      "capital": "", 
      "population": "2919", 
      "population_proper": "2919"
    }, 
    {
      "city": "Gyan Chak", 
      "latituide": "25.5496", 
      "longituide": "85.2423", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Bihār", 
      "capital": "", 
      "population": "2855", 
      "population_proper": "2855"
    }, 
    {
      "city": "Kasgatpur", 
      "latituide": "13.1101", 
      "longituide": "77.5045", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Karnātaka", 
      "capital": "", 
      "population": "2852", 
      "population_proper": "2852"
    }, 
    {
      "city": "Kitanelli", 
      "latituide": "13.0095", 
      "longituide": "77.4191", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Karnātaka", 
      "capital": "", 
      "population": "2827", 
      "population_proper": "2827"
    }, 
    {
      "city": "Harchandi", 
      "latituide": "25.1000", 
      "longituide": "87.0442", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Bihār", 
      "capital": "", 
      "population": "2827", 
      "population_proper": "2827"
    }, 
    {
      "city": "Santoshpur", 
      "latituide": "22.4650", 
      "longituide": "88.2193", 
      "country": "India", 
      "iso2": "IN", 
      "state": "West Bengal", 
      "capital": "", 
      "population": "2808", 
      "population_proper": "2808"
    }, 
    {
      "city": "Bendravādi", 
      "latituide": "12.3636", 
      "longituide": "76.9137", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Karnātaka", 
      "capital": "", 
      "population": "2684", 
      "population_proper": "2684"
    }, 
    {
      "city": "Kodagihalli", 
      "latituide": "12.9771", 
      "longituide": "77.4651", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Karnātaka", 
      "capital": "", 
      "population": "2585", 
      "population_proper": "2585"
    }, 
    {
      "city": "Harna Buzurg", 
      "latituide": "25.0981", 
      "longituide": "87.0148", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Bihār", 
      "capital": "", 
      "population": "2579", 
      "population_proper": "2579"
    }, 
    {
      "city": "Mailanhalli", 
      "latituide": "13.1863", 
      "longituide": "77.6963", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Karnātaka", 
      "capital": "", 
      "population": "2543", 
      "population_proper": "2543"
    }, 
    {
      "city": "Sultānpur", 
      "latituide": "25.5248", 
      "longituide": "85.2507", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Bihār", 
      "capital": "", 
      "population": "2473", 
      "population_proper": "2473"
    }, 
    {
      "city": "Adakimāranhalli", 
      "latituide": "13.0633", 
      "longituide": "77.4417", 
      "country": "India", 
      "iso2": "IN", 
      "state": "Karnātaka", 
      "capital": "", 
      "population": "2453", 
      "population_proper": "2453"
    }
  ]
  