module.exports = {
    descriptors: [
        'Forest', 'Ancient', 'Petrified', 'Roaring', 'Cascade', 'Tumbling', 
        'Silent', 'Redwood', 'Bullfrog', 'Maple', 'Misty', 'Elk', 'Grizzly', 
        'Ocean', 'Sea', 'Sky', 'Dusty', 'Diamond'
    ],
    places: [
        'Flats', 'Village', 'Canyon', 'Pond', 'Group Camp', 'Horse Camp', 
        'Ghost Town', 'Camp', 'Dispersed Camp', 'Backcountry', 'River', 'Creek', 
        'Creekside', 'Bay', 'Spring', 'Bayshore', 'Sands', 'Mule Camp', 
        'Hunting Camp', 'Cliffs', 'Hollow'
    ],
    descriptions:[
        'Rishikesh (Uttarakhand)- Nestled along the Ganges, this campsite offers riverside views, adventure sports, and serene yoga retreats.',  
'Spiti Valley (Himachal Pradesh)- Camp amidst barren landscapes, high-altitude monasteries, and a sky full of stars.',  
'Jaisalmer Desert Camp (Rajasthan)- Experience golden dunes, camel safaris, and traditional folk performances under the desert sky.',  
'Pawna Lake (Maharashtra)- A serene lakeside camping spot near Lonavala, perfect for bonfires and stargazing.',  
'Coorg (Karnataka)- Wake up to misty coffee plantations, gushing streams, and lush greenery.',  
'Chopta (Uttarakhand)- Known as the "Mini Switzerland of India," this campsite is a trekker’s paradise with stunning Himalayan views.',  
'Tso Moriri (Ladakh)- A remote and pristine high-altitude campsite beside a stunning blue lake.',  
'Mawlynnong (Meghalaya)- Camp in Asia’s cleanest village amidst waterfalls, living root bridges, and lush greenery.',  
'Kanatal (Uttarakhand)- A hidden gem near Mussoorie with apple orchards, forests, and breathtaking Himalayan views.',  
'Sattal (Uttarakhand)- A quiet lakeside camping destination surrounded by pine and oak forests.',  
'Wayanad (Kerala)- Camp amidst dense forests, waterfalls, and tea plantations in Kerala’s green paradise.',  
'Ranthambore (Rajasthan)- Experience wildlife camping near the famous tiger reserve with bonfires and jungle safaris.',  
'Tawang (Arunachal Pradesh)- High-altitude camping with Buddhist monasteries and snow-clad peaks in the background.',  
'Ziro Valley (Arunachal Pradesh)- A tranquil campsite surrounded by rice fields, misty hills, and Apatani tribal culture.',  
'Sundarbans (West Bengal)- Jungle camping in the world’s largest mangrove forest, home to the Royal Bengal Tiger.',  
'Hampi (Karnataka)- Camp among boulders, ancient ruins, and the magical Tungabhadra River.',  
'Chandratal Lake (Himachal Pradesh)- A mesmerizing crescent-shaped lake, perfect for high-altitude camping.',  
'Jim Corbett National Park (Uttarakhand)- Camp in the wilderness with the sounds of the jungle and thrilling safaris.',  
'Andaman Islands (Andaman & Nicobar)- Beach camping on pristine shores with snorkeling and bioluminescent waters.',  
'Kodaikanal (Tamil Nadu)- Experience misty mountain camping amidst pine forests and beautiful lakes.',  
'Mcleodganj (Himachal Pradesh)- A Tibetan-influenced camping retreat near the Triund trek with panoramic views.',  
'Rann of Kutch (Gujarat)- Stay in white desert camps and witness the surreal beauty of the Rann Utsav.',  
'Mukteshwar (Uttarakhand)- Enjoy panoramic Himalayan views and apple orchard camping in this hidden retreat.',  
'Lonavala (Maharashtra)- A perfect weekend getaway for camping amidst hills, waterfalls, and caves.',  
'Yercaud (Tamil Nadu)- A lesser-known hill station with coffee plantations and peaceful lake camping.',  
'Malshej Ghat (Maharashtra)- Monsoon camping destination with waterfalls, lush greenery, and birdwatching.',  
'Dhanaulti (Uttarakhand)- A peaceful camping spot near Mussoorie with dense forests and snow-capped views.',  
'Kasol (Himachal Pradesh)- A backpacker’s paradise with riverside camps and views of the Parvati Valley.',  
'Tamhini Ghat (Maharashtra)- A monsoon camping hotspot with waterfalls, greenery, and misty hills.',  
'Gokarna Beach (Karnataka)- Enjoy beachfront camping with the sound of waves and stunning sunset views.',  
'Vagamon (Kerala)- A cool and misty camping destination with rolling meadows and pine forests.',  
'Rajmachi Fort (Maharashtra)- Trek to this historic fort for a night of camping with mesmerizing valley views.',  
'Chakrata (Uttarakhand)- An offbeat Himalayan camping spot with waterfalls and thick deodar forests.',  
'Doddamakali (Karnataka)- A riverside camping retreat near the Kaveri River, perfect for birdwatching.',  
'Tirthan Valley (Himachal Pradesh)- A peaceful camping destination with trout fishing and lush forests.',  
'Mechuka (Arunachal Pradesh)- A remote valley campsite with Buddhist monasteries and stunning landscapes.',  
'Velas Beach (Maharashtra)- Beach camping during the famous turtle festival, where hatchlings make their way to the sea.',  
'Sandakphu (West Bengal)- The highest peak in Bengal, offering breathtaking camping with views of Kanchenjunga.',  
'Agumbe (Karnataka)- A rainforest camping experience in India’s ‘Cherrapunji of the South.’',  
'Kanha National Park (Madhya Pradesh)- A thrilling camping experience in one of India’s best tiger reserves.',  
'Mahabaleshwar (Maharashtra)- Camping in the strawberry capital with misty views and stunning viewpoints.',  
'Madikeri (Karnataka)- A scenic Coorg camping spot with waterfalls and spice plantations.',  
'Hemkund Sahib (Uttarakhand)- A spiritual and high-altitude camping trek with glacial lake views.',  
'Sariska National Park (Rajasthan)- A wildlife camping experience with safaris and the ruins of ancient temples.',  
'Araku Valley (Andhra Pradesh)- A lush green valley camping retreat with waterfalls and coffee plantations.',  
'Netarhat (Jharkhand)- Known as the ‘Queen of Chotanagpur,’ it’s a peaceful hilltop camping destination.',  
'Bundi (Rajasthan)- A heritage camping experience near blue-painted houses and ancient stepwells.',  
'Sillery Gaon (West Bengal)- A hidden camping gem in North Bengal with serene forests and a Kanchenjunga backdrop.'  
    ]
};
